
package gui;

import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.TextAyarlari;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ahmet Faruk
 */
public class MudurHesapEkrani extends javax.swing.JFrame {

    Connection con =null;
    PreparedStatement pst =null;
    ResultSet rs  = null;
         
    
    public MudurHesapEkrani() {
        initComponents();
        this.setLocationRelativeTo(null);
        mudurHesapLabel.setFocusable(true);
        ShowTableData1();
        ShowTableData2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mudurHesapLabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayData = new javax.swing.JTable();
        EkleButton = new javax.swing.JButton();
        SilButton = new javax.swing.JButton();
        GuncelleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AdSoyadText = new javax.swing.JTextField();
        TcNoText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        TelNoText = new javax.swing.JTextField();
        adresText = new javax.swing.JTextField();
        TemsilciNotext = new javax.swing.JTextField();
        MusteriNoText = new javax.swing.JTextField();
        SifreText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kullaniciIDtext = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bakiyetablosu = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        geriLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müdür Hesap Ekranı");

        mudurHesapLabel.setBackground(new java.awt.Color(204, 204, 255));

        displayData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "kullanici_id", "Ad Soyad", "tcNo", "telNo", "e_mail", "adres", "temsilci_no", "müşteri_no", "şifre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayData);

        EkleButton.setBackground(new java.awt.Color(204, 255, 204));
        EkleButton.setText("Ekle");
        EkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleButtonActionPerformed(evt);
            }
        });

        SilButton.setBackground(new java.awt.Color(255, 153, 153));
        SilButton.setText("Sil");
        SilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilButtonActionPerformed(evt);
            }
        });

        GuncelleButton.setBackground(new java.awt.Color(255, 255, 153));
        GuncelleButton.setText("Güncelle");
        GuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelleButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MÜDÜR HESAP EKRANI");

        jLabel2.setText("Ad Soyad :");

        jLabel3.setText("TC no :");

        jLabel4.setText("Tel No :");

        jLabel5.setText("E- mail :");

        jLabel6.setText("Adres :");

        jLabel7.setText("Temsilci No :");

        jLabel8.setText("Müsteri No :");

        jLabel9.setText("Şifre :");

        AdSoyadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdSoyadTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Kullanici ID :");

        bakiyetablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "kullanici_id", "bakiye", "musteri_no"
            }
        ));
        jScrollPane2.setViewportView(bakiyetablosu);

        jLabel11.setText("KULLANICILAR TABLOSU");

        jLabel12.setText("BAKİYE TABLOSU");

        geriLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/previousIcon.png"))); // NOI18N
        geriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mudurHesapLabelLayout = new javax.swing.GroupLayout(mudurHesapLabel);
        mudurHesapLabel.setLayout(mudurHesapLabelLayout);
        mudurHesapLabelLayout.setHorizontalGroup(
            mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TcNoText)
                                .addComponent(TelNoText)
                                .addComponent(EmailText)
                                .addComponent(adresText)
                                .addComponent(TemsilciNotext)
                                .addComponent(MusteriNoText)
                                .addComponent(SifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geriLabel)
                            .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdSoyadText)
                                    .addComponent(kullaniciIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                        .addComponent(GuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudurHesapLabelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudurHesapLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(377, 377, 377))
        );

        mudurHesapLabelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EkleButton, GuncelleButton, SilButton});

        mudurHesapLabelLayout.setVerticalGroup(
            mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geriLabel)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mudurHesapLabelLayout.createSequentialGroup()
                        .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudurHesapLabelLayout.createSequentialGroup()
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(AdSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TelNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(adresText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(TemsilciNotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(MusteriNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(SifreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudurHesapLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(GuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudurHesapLabelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        mudurHesapLabelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EkleButton, GuncelleButton, SilButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mudurHesapLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mudurHesapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdSoyadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdSoyadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdSoyadTextActionPerformed

    private void EkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleButtonActionPerformed
        try{
            String sql = "INSERT INTO kullanicilar" 
                    + "(ad_soyad,tc_no,tel_no,e_mail,adress,musteri_no,sifre,temsilci_no)"
                    + "VALUES (?,?,?,?,?,?,?,?)";
            con =DriverManager.getConnection("jdbc:mysql://localhost/sweet_bank", "root", "ah44994499.");
            pst= con.prepareStatement(sql);
            pst.setString(1,AdSoyadText.getText());
             pst.setString(2,TcNoText.getText());
               pst.setString(3,TelNoText.getText());
                 pst.setString(4,EmailText.getText());
                   pst.setString(5,adresText.getText());
                     pst.setString(6,MusteriNoText.getText());
                       pst.setString(7,SifreText.getText());
                         pst.setString(8,TemsilciNotext.getText());
                          
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Eklendi !");
             
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        ShowTableData1();
        ShowTableData2();
    }//GEN-LAST:event_EkleButtonActionPerformed

    private void SilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilButtonActionPerformed
       
           try{
            String sql = "DELETE FROM kullanicilar WHERE kullanici_id =?";
                   
            con =DriverManager.getConnection("jdbc:mysql://localhost/sweet_bank", "root", "ah44994499.");
            pst= con.prepareStatement(sql);
            pst.setString(1,kullaniciIDtext.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Silindi !");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
           ShowTableData1();
           ShowTableData2();
    }//GEN-LAST:event_SilButtonActionPerformed

    private void GuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelleButtonActionPerformed
        
          try{
            String sql = "UPDATE kullanicilar SET tel_no=?,temsilci_no=?,musteri_no=?,sifre=? WHERE kullanici_id =? ";
            con =DriverManager.getConnection("jdbc:mysql://localhost/sweet_bank", "root", "ah44994499.");
            pst= con.prepareStatement(sql);
            pst.setString(5,kullaniciIDtext.getText());
               pst.setString(1,TelNoText.getText());
                     pst.setString(2,TemsilciNotext.getText());
                       pst.setString(3,MusteriNoText.getText());
                         pst.setString(4,SifreText.getText());
                          
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Güncellendi !");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
          ShowTableData1();
          ShowTableData2();
        
    }//GEN-LAST:event_GuncelleButtonActionPerformed

    private void geriLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriLabelMouseClicked
         ActionAyarlari.setVisible(this, new GirisEkrani());
    }//GEN-LAST:event_geriLabelMouseClicked

    public void ShowTableData1(){
        try{
            con =DriverManager.getConnection("jdbc:mysql://localhost/sweet_bank", "root", "ah44994499.");
           String sql = "SELECT * FROM kullanicilar";
           pst= con.prepareStatement(sql);
           rs=pst.executeQuery();
           displayData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
       public void ShowTableData2(){
        try{
            con =DriverManager.getConnection("jdbc:mysql://localhost/sweet_bank", "root", "ah44994499.");
           String sql = "SELECT * FROM kullanici_bakiye";
           pst= con.prepareStatement(sql);
           rs=pst.executeQuery();
           bakiyetablosu.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
 
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in JmudurHesapLabel6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MudurHesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MudurHesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MudurHesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MudurHesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MudurHesapEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdSoyadText;
    private javax.swing.JButton EkleButton;
    private javax.swing.JTextField EmailText;
    private javax.swing.JButton GuncelleButton;
    private javax.swing.JTextField MusteriNoText;
    private javax.swing.JTextField SifreText;
    private javax.swing.JButton SilButton;
    private javax.swing.JTextField TcNoText;
    private javax.swing.JTextField TelNoText;
    private javax.swing.JTextField TemsilciNotext;
    private javax.swing.JTextField adresText;
    private javax.swing.JTable bakiyetablosu;
    private javax.swing.JTable displayData;
    private javax.swing.JLabel geriLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kullaniciIDtext;
    private javax.swing.JPanel mudurHesapLabel;
    // End of variables declaration//GEN-END:variables
}
